 


        <p>During the year 2011/2012 I was at the <a href="http://math.unifr.ch/">Department of Mathematics</a>, University of Fribourg, in Switzerland, in the research group of <a href="http://homeweb1.unifr.ch/kellerha/pub/">Ruth Kellerhals</a>. </p>
        
        <p>Before that I spent one year at <a href="http://www.mpim-bonn.mpg.de/">Max Planck Institute for Mathematics</a> in Bonn, Germany. </p>
